### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'scatter_reduce_'

### ISSUE THREAD

**Issue by amokame** [valeoai/WaffleIron#17]
I tried to train the model. get the following error.
I'm using pytorch=1.11.0+cu113.
Any idea why this happened? Thanks.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/workspace/launch_train.py", line 253, in distributed_training
    mng.train()
  File "/home/workspace/utils/trainer.py", line 290, in train
    self.one_epoch(training=True)
  File "/home/workspace/utils/trainer.py", line 166, in one_epoch
    out = net(*net_inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/workspace/waffleiron/segmenter.py", line 46, in forward
    tokens = self.waffleiron(tokens, cell_ind, occupied_cell)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/workspace/waffleiron/backbone.py", line 219, in forward
    tokens = smix(tokens, sp_mat[d % len(sp_mat)])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/workspace/waffleiron/backbone.py", line 175, in forward
    residual = projection_3d_to_2d(residual, sp_mat, B, C, self.H, self.W)
  File "/home/workspace/waffleiron/helper_projection.py", line 27, in projection_3d_to_2d_scatter_reduce
    residual.scatter_reduce_(
AttributeError: 'Tensor' object has no attribute 'scatter_reduce_'

**Comment by gpuy** [comment]
Hi @amokame 

The easiest solution is to switch to pytorch 2, if possible. See for example the second proposed environment [here](https://github.com/valeoai/WaffleIron/blob/master/README.md#installation).

This is happening because the `Tensor.scatter_reduce` does not exist in pytorch 1.11. With pytorch 1.11, I used sparse matrices to implement the projection from 3D to 2D. But this function stopped working correctly for pytorch>1.11 with batch sizes >= 2. I thus switched to `Tensor.scatter_reduce` to be able to use pytorch 2.

An automatic selection between the use of sparse matrices or `Tensor.scatter_reduce` is done [here](https://github.com/valeoai/WaffleIron/blob/master/waffleiron/__init__.py#L18). In your case, it might detect a wrong version of pytorch. 

You can force the use of sparse matrices by using `export WI_SCATTER_REDUCE=0` before launching the code. Alternatively `export WI_SCATTER_REDUCE=1` will force the use of `Tensor.scatter_reduce`.

**Comment by amokame** [comment]
@gpuy 
Thank you for your advice and thoughtful explanation!
I will try to install pytorch 2.
